### ISSUE TITLE
Inconsistent freezing of object

### ISSUE THREAD

**Issue by jfmengels** [substantial/updeep#38]
Hi there!

I stumbled accross some scenarios where the given object `u({}, object}` gets frozen, which I think is a bit odd and possibly surprising at times. (Note: I simply took the tests from test/updeep-spec.js, and added a new one)

The purpose in the following situation, is to create a "copy" of `object`, modify it using the `updates` parameter (here `{ foo: 4 }`), freeze and return it.
```js
it('can update with fixed values', () => {
  const object = { foo: 3, bar: [7, 5] };
  const result = u({ foo: 4 }, object);

  expect(result).to.deep.equal({ foo: 4, bar: [7, 5] });
  expect(Object.isFrozen(result)).to.be.true;  // --> OK
  expect(Object.isFrozen(object)).to.be.false; // --> OK
});
```
Thus, here we expected result to be frozen and to have the updated values, object to not be frozen and to not have been modified. All good here.

But a different thing happens when there are no changes to `object`. It then returns `object`, but also frozen. That is fine when `object` is already frozen because then we can't really consider as a side-effect, but if it isn't, it's a pretty surprising result.
```js
it('does not change anything if no updates are specified', () => {
  const object = { foo: 3, bar: [7, 5] };
  const result = u({}, object);

  expect(result).to.equal(object);
  expect(Object.isFrozen(result)).to.be.true;  // --> OK
  expect(Object.isFrozen(object)).to.be.false; // --> Fails
});

it('should not freeze passed object when it does not change', () => {
  // This seems to me like a possible real-world scenario, unlike when using u({}, object)
  const object = { foo: 3, bar: [7, 5] };
  const result = u({ foo: 3 }, object);

  expect(result).to.equal(object);
  expect(Object.isFrozen(result)).to.be.true;  // --> OK
  expect(Object.isFrozen(object)).to.be.false; // --> Fails
});
```
Maybe we'll dispatch it to Redux and afterwards start mutating `object`, not knowing or thinking that it might have become frozen.

From what I understood, the idea it is to not change the reference if the value didn't change, so that we can notice changes by comparing the previous and the new version of the object. Here, it looks to me that it is potentially harmful.

What to do? Either
* Simply document this particular case (if it is, I didn't find it... might be me, or it might be better )
* Return a "clone" of `object` if there are no changes but `object` is not frozen (which is IMO a breaking change).
* or something else that I didn't think of

Neither one is great IMO, but hey, I haven't even started using it (though definitely considering it) so I'm not qualified to say anything, but I found this when playing with it for a few minutes, and I thought it was pretty weird.

Apart from this, the library looks promising. I was just considering switching from Immutable.js to seamless-immutable, and while reading through it I found updeep. Definitely considering switching to updeep now (the update functions look pretty powerful compared to seamless).

**Comment by aaronjensen** [comment]
Hey @jfmengels thanks for the detailed report.

This is a tricky one, and I've thought about it in the past, so the current behavior is a conscious decision. It may be the wrong one, however :smile:

Here's my reasoning:

1. updeep is for use with immutable values. Passing mutable things into updeep isn't really something I've cared to handle gracefully as I assume people don't tend to want to immutably update mutable things. 
2. A deep clone could work, but it's very expensive, so I'd rather leave that up to the user if they are knowingly needing to update a mutable thing.
3. Freezing only happens in development, not in production, so I wouldn't even really be able to detect when I should or I should not deep clone in production unless I "tagged" objects that would have otherwise been frozen, but that adds overhead.

I'm not even really sure how to warn about it other than documentation. I think that it's a fairly discoverable thing (as you have discovered) because if you pass something in and then later try to mutate it, you'll hit this--at least in dev.

**Comment by jfmengels** [comment]
Hey @aaronjensen 
I guessed it was a conscious decision, and I also don't know if it's the right one or not. I'm guessing that in the use case you are using it for (Redux), it's probably the better one.

I support the idea of putting it in the readme, so that you at least won't get any new issue reports such as this one ;). Especially if no crash/error is created when mutating the value in production (because it won't actually be frozen), since there will be no easy way for the developer to notice the cause of his possible data mutation, if his tests aren't exhaustive enough.

Now that I know that this is not a bug (or a " known and conscious bug" maybe), I feel more secure trying out and switching to updeep :)

**Comment by aaronjensen** [comment]
@jfmengels great, feel free to reach out if you have other questions. I've updated the readme with some more verbiage around this: 43d34e0

**Comment by jfmengels** [comment]
Looks okay to me, thanks a lot!
