### ISSUE TITLE
Make freezing optional?

### ISSUE THREAD

**Issue by peteruithoven** [substantial/updeep#41]
Is there any way to use updeep without freezing my data? I'm porting old code to Redux, which I'm doing in steps, which means I have some parts I need to mutate. 
Would be great if freezing was optional.

**Comment by peteruithoven** [comment]
This could be a usecase for https://github.com/substantial/updeep/issues/37 ?

**Comment by aaronjensen** [comment]
Are you wanting freezing to be optional, or do you actually want updeep to mutate objects in place? If it's the former, and you're ok with the fact that updeep will return new instances, and you're using webpack, You could use the `NormalModuleReplacementPlugin` to replace the `freeze` module probably: https://webpack.github.io/docs/list-of-plugins.html#normalmodulereplacementplugin If it's the latter, I don't think I'm going to move updeep to optionally mutate, because imperative mutation works pretty well for that.

FWIW, we ported an app to redux one store at a time, extracting the reducer and making it work w/o mutation at the same time. This was the motivation for updeep, to make that easier.

**Comment by peteruithoven** [comment]
The freezing part. It should defiantly still return new objects, basically I want to enable the freezing when I porting is "done". 
My code is coming from a system that has data objects with getters and setters and that emit events when changes are made, so until those are ported I can't freeze those objects. 

I'm using JSPM, I'll look into that option.

**Comment by aaronjensen** [comment]
Gotcha, yeah, for now, I'd look into module replacement of some sort. Alternatively, you could use a fork of updeep while you convert.

**Comment by aaronjensen** [comment]
I'm going to close this out, I don't think this should be built into updeep at this time, it's too confusing.
