### ISSUE TITLE
Proposal to make freezing optional

### ISSUE THREAD

**Issue by gilbox** [substantial/updeep#57]
I think you should reconsider adding the feature proposed in https://github.com/substantial/updeep/issues/41 because it makes `updeep` easier to adopt. There are valid use cases to not use freezing in development even if you're never editing an object in-place. Also, requiring that users modify their build configuration with module replacement is adding too much friction to adoption, imo.

It can be done without effecting the existing api by having a separate import like.

```
import u from 'updeep/nofreeze';
```

It would require refactoring the existing code so that *wrap*ing is performed in `index.js` instead of each individual file like `map.js`. I can submit a PR for this if you're open to the suggestion.

**Comment by aaronjensen** [comment]
Hi @gilbox, one of my biggest concerns that I don't think I voiced in that thread is that updeep doesn't really work when mutation is involved since it itself does not mutate and it reuses objects and arrays when it can, meaning that if you were to use updeep to make an update to something and then later mutate either the input or the output, you could inadvertently be updating the other, which could be very surprising to people. 

That said, another option to get a non-freezing version of updeep is to simply use a production build. Just:

```js
import u from 'updeep/dist/umd/updeep-standalone.min'
```

That should give you a non-freezing build today. Or, if you want a non-minified version, you could compile it yourself with NODE_ENV=production

**Comment by gilbox** [comment]
> if you were to use updeep to make an update to something and then later mutate either the input or the output, you could inadvertently be updating the other, which could be very surprising to people.

It's true, but if you are advanced enough to be using updeep you should be away of this possibility.

IMO, a minified/production build in dev is not any better (probably worse) than using module replacement.

**Comment by aaronjensen** [comment]
> IMO, a minified/production build in dev is not any better (probably worse) than using module replacement.

Why is that? 

I'd probably accept a pull request that adds an undocumented or heavily caveated additional build that had freezing disabled by just using NODE_ENV=production (or some other webpack flag). It doesn't need code changes, freeze disabling is already there.

**Comment by gilbox** [comment]
oh cool i think you're right that's probably the best way...

**Comment by gilbox** [comment]
https://github.com/substantial/updeep/pull/59
