### ISSUE TITLE
cool project

### ISSUE THREAD

**Issue by gilbox** [substantial/updeep#6]
Just thought I'd share how I'm using this, feel free to close this issue i you think it's off-topic....

I'm not using redux nor flux. Instead, my components edit state directly, although still in a top-down manner. To this end, my goal was to create an *edit* function that gets passed to a component so that component only has access to the state it manages. As you know, updeep basically supports that this way:

```
import u from 'updeep';
const immutable = u({});

let state = immutable({ items: [ {name: 'foo'}, {name:'bar'} ] });

const edit = transform => transform(state);
const editItems = transform => edit(u({ items: transform }));
const editSecondName = transform => editItems( u({ 1: { name: transform }}) );

state = editSecondName(name => 'max');
console.log(state); // => 'max';
```

I [experimented](https://github.com/gilbox/elegant-react/blob/updeep/examples/reorder-items-updeep/app.js) with the syntax above but felt it was overly verbose for this use-case. Also made [a second attempt](https://github.com/gilbox/elegant-react/blob/updeep-2/examples/reorder-items-updeep/app.js) but it still seemed too complicated.

I like the syntax of updeep, but I think the single-path update is a common use-case (in my project) which would benefit from a simpler syntax. So I created this `sub`edit function...

```
const sub = (edit, ...path) => {
  const updates = {};
  const lastIndex = path.length - 1;
  let subUpdates = updates;
  
  path.forEach((p,index) => {
    if (index === lastIndex) return;
    subUpdates = subUpdates[p] = {};
  });

  return xf => {
    subUpdates[path[lastIndex]] = xf;
    return edit(u(updates));
  };
}
```

now I can do this

```
import u from 'updeep';
const immutable = u({});

let state = immutable({ items: [ {name: 'foo'}, {name:'bar'} ] });

const edit = transform => transform(state);
const editItems = sub(edit, 'items');
const editSecondName = sub(editItems, 1, 'name');

state = editSecondName(name => 'max');
console.log(state); // => 'max'
```

And a real example...

Here's [how I use it with react](https://github.com/gilbox/elegant-react/blob/master/examples/reorder-items-updeep/app.js) and here is the [live version of the same thing using immutable-js](http://gilbox.github.io/elegant-react/examples/reorder-items/demo.html)

btw, I think there might be a simpler way to do this. let me know if you have any ideas.

**Comment by aaronjensen** [comment]
Very cool use case and ideas. Thanks for sharing.

Your `immutable` is great... I was actually planning to expose `u.freeze` but forgot to. Looks like a no-brainer now :smile:

For setting a simple path, what about something like:

```js
u.set('1.name.first', 'Bob', state);

// It would be curried, so you could do:
u.set('1.name.first', 'Bob')(state);

// and even:
u.set('1.name.first')('Bob')(state);
```

This even allows it to be nested in a full update:

```js
u({
  people: u.set('1.name.first', 'Bob'),
  // ...
});
```

It could also take an array as the first param if interpolated strings are too much:

```js
u.set([index, property, otherProperty], 'Foo', state);
```

**Comment by gilbox** [comment]
I like the idea of exposing freeze because it eliminates a line of code.

The one change I'd make to the syntax you mentioned is to pass in a transform function, not the value. 

So instead of

```
u.set([index, property, otherProperty], 'Foo', state);
```

use

```
u.set([index, property, otherProperty], value => 'Foo', state);
```

although the word "set" might not be the best name but this alternative since set usually implies passing in a value. Ignoring that for the moment, I think that the `sub`edit function would be as simple as this:

```
import u, {set, freeze} from 'updeep';

const sub = (edit, ...path) => transform => set(path, transform)

let state = freeze({ items: [ {name: 'foo'}, {name:'bar'} ] });

const edit = transform => transform(state);
const editItems = sub(edit, 'items');
const editSecondName = sub(editItems, 1, 'name');

```

**Comment by mindjuice** [comment]
I like both the string path and array versions. :+1:

It would be good for ``set()`` to accept either a value or a function, not just a function.

I don't think that getting the final value from a function makes the name ``set()`` less relevant though.  In the end, you're still setting a property value.

I do, however, wonder if there is a better name, since updeep data is immutable, and ``set`` implies mutation.  I can't think of anything better though!  The name ``copySomeSubsetOfThisStructureExceptThePartsThatCanBeSafelySharedButWithSomePropertiesHavingDifferentValuesAsSpecifiedHereafter()`` doesn't roll off the tongue quite as nicely.

**Comment by aaronjensen** [comment]
Good call on taking a function, though I agree w/ @mindjuice that it could accept either. I actually considered making it part of the standard `update`/`u` function, but didn't like the idea of having to write my own currying that'd have to type check the first argument to decide between the 2 or 3 argument version, or the confusion that comes w/ variable arity (esp when the new arguments are inserted rather than appended).

A common name for this operation is `updateIn`: [icepick](https://github.com/aearly/icepick#updateincollection-path-callback) [clojure](http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/update-in). I tend to think of the `u` as standing for `update`, so I think I may go w/ `u.in`. It's even shorter than set, which is a good thing for something that'll probably be common.

**Comment by gilbox** [comment]
+1 `u.in`

**Comment by aaronjensen** [comment]
Just release 0.3.0 w/ `u.in` and `u.freeze`. lmk how they work out. I also updated the docs, any feedback on them would be appreciated. Thanks!

**Comment by aaronjensen** [comment]
Sorry, 0.3.1

**Comment by aaronjensen** [comment]
@gilbox @mindjuice Do you think I got the order of the arguments right?

I'm wondering if it would have made more sense to put the value first, followed by the path. It really only matters if people are wanting to curry it one way and not another. I could always support `_.curry.placeholder` (It actually probably does support it already...)

**Comment by mindjuice** [comment]
I suspect you would be more likely to want to have a curried function that writes different values to the same path than the same value to different paths, but either is potentially reasonable.  You can always write your own partially applied wrapper function too.  I'm not familiar with placeholder, though, so maybe that's what it does.  I couldn't find a good explanation after a quick Google.

**Comment by aaronjensen** [comment]
Cool, I'll keep it as is. I also like that it keeps the same direction as `key: value`.

re: placeholder, see https://lodash.com/docs#curry

example from the docs here:

```js
var abc = function(a, b, c) {
  return [a, b, c];
};

var curried = _.curry(abc);

// using placeholders
curried(1)(_, 3)(2);
// → [1, 2, 3]
```

Basically, it lets you partially apply in any order you like. You just specify the placeholder for arguments you don't want to pass yet.

**Comment by mindjuice** [comment]
Makes sense.  Thanks!
