### ISSUE TITLE
Attempts to freeze unfreezable (3rd party) objects

### ISSUE THREAD

**Issue by davidgoli** [substantial/updeep#69]
We're implementing a Redux component wrapping the Google Maps API, which loads a global `google` object via a `<script>` tag that gets attached to the `window` object. We're trying to Reduxify this approach by attaching the `google` object to the state tree instead, but the `google` object is a proprietary 3rd party object with some unknown minified contents that throw errors upon attempts to freeze.

It would be very helpful to have `u.unfreezable()` wrapper that would always avoid freezing its contents for scenarios like this - to allow for 3rd party mutable exceptions on an otherwise immutable state tree. I realize this has potential for abuse, but hoping its opt-in nature will make it the exception.

**Comment by aaronjensen** [comment]
Hey @davidgoli, thanks for the report. We discussed in real life, but I'll record here for posterity.

The issue was that you were sending the Google Maps object as it was to updeep, something like: 

```js
u({ google }, state)
```

One of the powers of updeep is also its biggest surprise. Updeep will see any function within `google` as an update function, which means it will call it. What you really want here is to either use `u.constant` or an anon function:

```js
u({ google: u.constant(google) }, state)
u({ google: () => google) }, state)
```

That will tell updeep you just want to replace the value and not use it to "update" an existing value.

Of course, at this point, you don't actually need updeep if you have object spread:

```js
{ ...state, google }
```

Please let me know if you run into any more issues. Thanks!
